### ISSUE TITLE
Unsubscribe not being called

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/aor-realtime#3]
This is based on the small chat we had over at admin-on-rest. I tried figuring out why, but so far no luck.

**Comment by RWOverdijk** [comment]
Haha, it's subscribing but not unsubscribing. So I'm making around 100 requests a second now, after navigating around for a bit.

**Comment by djhi** [comment]
Yes, I found the problem. Probably won't be able to fix it before next week though.

**Comment by RWOverdijk** [comment]
@djhi Could you tell me what it is? Maybe I can fix it. I have time now :) Maybe also add info on the other issues so I can tackle those, too.

**Comment by djhi** [comment]
Sure, we should:
- remove the current `watchLocationChangeFactory` in `index.js`
- update the `takeEvery` so that it takes CRUD_GET_LIST, CRUD_GET_ONE and LOCATION_CHANGE
- in the saga, inside the loop, check the action type
    - if type is LOCATION_CHANGE and an observer exists => unsubscribe
    - create the observer like before

**Comment by RWOverdijk** [comment]
@djhi I can't find `takeEvery` anywhere in the project. Do you mean `takeLatest`?

`yield takeLatest([CRUD_GET_LIST, CRUD_GET_ONE], watchCrudActions);`

**Comment by djhi** [comment]
Yes, sorry about that

**Comment by djhi** [comment]
Any luck ?

**Comment by RWOverdijk** [comment]
Very little... I'd need to store the active subscription outside of the sage so I can reference it next time to unsubscribe. It feels icky. I'm attempting a new approach where it's not solved using a saga, but custom actions on the List.

**Comment by djhi** [comment]
Why icky ? In case you want multiple observers at the same time ?

**Comment by RWOverdijk** [comment]
No, because that's the type of stuff that doesn't belong in a saga. That's component logic. Sagas should do their saga thing. Not dispatch anything all over.

**Comment by djhi** [comment]
Can you elaborate about the custom actions on the List ?

Are you planning to have a component rendering a list and dispatching a `WATCH_QUERY_IN_REAL_TIME` action when it mounts ?

**Comment by RWOverdijk** [comment]
@djhi Sort of. I was looking at https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/List.js#L191 and it looks like you get refresh. Which, if true, could allow you to fire off an event periodically yourself. You could even wait for the finish event before firing the next one after a timeout. It could even be a wrapper that does nothing, and by default proxies to DefaultActions.

**Comment by djhi** [comment]
Ok so you won't be using `aor-realtime` at all right ?

**Comment by RWOverdijk** [comment]
If that works, then no, I think that's a better place to do it personally. But the real time plugin could become a provider for this logic deeper down the tree. I'd like to solve it elegantly.

It's either that or adding a refresh action. I don't know if the filters and page are part of the store, but that would be the best way to do it altogether,

**Comment by djhi** [comment]
Have you noticed this PR about refresh: https://github.com/marmelab/admin-on-rest/pull/942 ? That should address your concern. However, that wasn't the point of this addon. It's meant to add real time feature automatically and to allow including websockets or graphql subscriptions.

**Comment by RWOverdijk** [comment]
Well obviously I haven't haha. Wouldn't that be much better for the aor-realtime lib? Then it can check what is the active resource and allow you to configure which ones to watch, with what interval?

Either way, that would allow me to just dispatch REFRESH_VIEW, and it would do the same as clicking the button? If so, last question (sorry for that) do you have an example on how to link that in a List? I'm guessing I'll have to just connect() my list to get access to dispatch?

**Comment by djhi** [comment]
> Wouldn't that be much better for the aor-realtime lib? Then it can check what is the active resource and allow you to configure which ones to watch, with what interval?

Nope it won't: using the refresh action would make the client trigger another request. However, the goal of this addon is to allow other mechanisms to update the data: think about websockets, firebase, pouchb, graphql subscriptions, etc.

> Either way, that would allow me to just dispatch REFRESH_VIEW, and it would do the same as clicking the button? If so, last question (sorry for that) do you have an example on how to link that in a List? I'm guessing I'll have to just connect() my list to get access to dispatch?

Exactly :)

**Comment by RWOverdijk** [comment]
Ah that's fair yes... I'll attempt to fix it anyway, if I can't I'll comment again.

**Comment by RWOverdijk** [comment]
@djhi I can solve the bug "hacky" by only changing createObserverChannel"

```js
import { eventChannel } from 'redux-saga';
import queryObserver from './queryObserver';

let activeWatcher;

export const queryObserverFactory = queryObserverImpl => (watcher, emitter) => {
    const observer = queryObserverImpl(emitter);

    if (activeWatcher) {
      activeWatcher.unsubscribe();

      activeWatcher = null;
    }

    activeWatcher = watcher.subscribe(observer);

    const unsubscribe = () => {
        observer.unsubscribe();
    };

    return unsubscribe;
};

export default watcher => eventChannel(emitter => queryObserverFactory(queryObserver)(watcher, emitter));
```

I can't remove the unsubscribe constant because whatever it's used for expects a function. That's why I'd say this is definitely hacky :p 

**Update:** [found a link ](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Channels.md) explaining it... Reading now.

**Update:** Lost myself in building the other solution https://github.com/marmelab/admin-on-rest/issues/970#issuecomment-324894628 and I'm officially using this comment as my diary

**Update:** Just had an "aha!" moment reading about redux channels, only to then quickly go back to only partially getting it. I'm getting closer.
