### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/aor-realtime#4]
> [...effects] has been deprecated in favor of all([...effects]), please update your code

**Comment by djhi** [comment]
Can't figure out where we use this pattern. Are you sure it's related to `aor-realtime` and not `admin-on-rest` ?

**Comment by RWOverdijk** [comment]
I'm not sure, no. It's being triggered by `emitter(apolloQueryResult);` in queryObserver.js.

**Comment by djhi** [comment]
We have the same warnings on the demo which does not use `aor-realtime`. That most probably come from `admin-on-rest`

**Comment by RWOverdijk** [comment]
@djhi Want me to open up an issue there?

**Comment by djhi** [comment]
Yes, sure :)
